let @t="viwdi<paramref name=\"€ýapa\"/>€ýa"
let @y="viwdi<see cref=\"€ýapa\"/>€ýa"
let @m="Go<remarks>\<CR></remarks>\<Esc>"
let @n="Go<returns>\<CR></returns>\<Esc>"
let @p="viwyGo<param name=\"pa\"></param>?>\<Return>a"